%% Data:
fileName = {'10.mat', '-10.mat', ...
    '20.mat', '-20.mat', ...
    '30.mat', '-30.mat', ...
    '40.mat', '-40.mat' };

% training:
trainingData = [];
for i = 1:length(fileName)
    currentData = [];
    load(fullfile('C:\Users\Aleksander\Documents\MATLAB\STL', fileName{i}));
    currentData = [out.state_data, ...
        out.control_input_data];
    trainingData = [trainingData; currentData];
end


%% Setup: (sequence to one)
numInput = 1; % sequence 4x1 
numResponses = 1; % one 1
 
% LSTM:
numHiddenUnits = 100;
layers = [ ...
    sequenceInputLayer(numInput, Normalization="zscore")
    lstmLayer(numHiddenUnits, OutputMode="last")
    fullyConnectedLayer(numResponses)
    regressionLayer];

options = trainingOptions("adam", ...
    MaxEpochs=2000, ...
    ValidationData= ...
    {num2cell(trainingData(:,1:4),2) ...
    trainingData(:,5)}, ...
    OutputNetwork="best-validation-loss", ...
    InitialLearnRate=0.001, ...
    SequenceLength="shortest", ...
    Plots="training-progress", ...
    Verbose= false);

policy = trainNetwork(num2cell(trainingData(:,1:4),2),...
    trainingData(:,5), layers, options);
